###########
# site.title, site.url, site.author.name

title:   'Wei Chen'
author:  
  name:  'Wei Chen'
description:  'First-principles methods, defect physics, and data-driven materials discovery'

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path:
url:  'https://wch3n.github.io'


########
# more settings

markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md


safe: true
lsi: false
